kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.name }}
  labels:
    app_name: {{ .Values.name }}
    app_version: {{ .Values.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  revisionHistoryLimit: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app_name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app_name: {{ .Values.name }}
        app_version: {{ .Values.image.tag | quote }}
        helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 12345
        livenessProbe:
          httpGet:
            path: /hello
            port: 12345
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /hello
            port: 12345
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}