apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app_name: {{ .Values.name }}
    app_version: {{ .Values.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.serviceType | quote }}
  selector:
    app_name: {{ .Values.name }}
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 12345