FROM golang:latest
MAINTAINER Somya Garg <contact.somyagarg@gmail.com>

ENV GOOS linux
ENV CGO_ENABLED 0

RUN mkdir -p /go/src/github.com/somyagarg94/helloservice
WORKDIR /go/src/github.com/somyagarg94/helloservice